### ISSUE TITLE
routerHelper.ts报错packageViews is not defined

### ISSUE THREAD

**Issue by hdtopku** [jeecgboot/jeecgboot-vue3#165]
##### 版本号：
3.4.2

##### 问题描述：
routerHelper.ts 应该添加import
```
import { packageViews } from '/@/utils/monorepo/dynamicRouter';

```
最新代码报错：

```
index.d31032cf.js:124 ReferenceError: packageViews is not defined
    at asyncImportRoute (index.d31032cf.js:160:339929)
    at index.d31032cf.js:160:342211
    at Array.forEach (<anonymous>)
    at transformObjToRoute (index.d31032cf.js:160:341837)
    at Proxy.<anonymous> (index.d31032cf.js:160:350006)
    at Generator.next (<anonymous>)
    at Q (index.d31032cf.js:1:670)
Te @ index.d31032cf.js:124
（匿名） @ index.d31032cf.js:124
Promise.catch（异步）
he @ index.d31032cf.js:124
he @ index.d31032cf.js:124
fe @ index.d31032cf.js:124
install @ index.d31032cf.js:124
use @ index.d31032cf.js:4
setupRouter @ index.d31032cf.js:151
（匿名） @ index.d31032cf.js:205
Q @ index.d31032cf.js:1
Promise.then（异步）
X @ index.d31032cf.js:1
Q @ index.d31032cf.js:1
Promise.then（异步）
X @ index.d31032cf.js:1
（匿名） @ index.d31032cf.js:1
Kt @ index.d31032cf.js:1
bootstrap @ index.d31032cf.js:205
（匿名） @ index.d31032cf.js:205
index.d31032cf.js:160 Uncaught (in promise) ReferenceError: packageViews is not defined
    at asyncImportRoute (index.d31032cf.js:160:339929)
    at index.d31032cf.js:160:342211
    at Array.forEach (<anonymous>)
    at transformObjToRoute (index.d31032cf.js:160:341837)
    at Proxy.<anonymous> (index.d31032cf.js:160:350006)
    at Generator.next (<anonymous>)
    at Q (index.d31032cf.js:1:670)
```

##### 截图&代码：

![image](https://user-images.githubusercontent.com/14859466/195081936-22303186-9a80-4e84-9475-d03e6f4142dc.png)

routerHelper.ts 有错：

![image](https://user-images.githubusercontent.com/14859466/195082099-3e1490cc-6606-4ca6-8130-59f19dc0e31f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by popbayun** [comment]
调试解决之后才看到这个。。。。。同问为啥把那个import给删了

**Comment by zhangdaiscott** [comment]
修复了
