### ISSUE TITLE
在线表单的自定义按钮无法使用多行选择

### ISSUE THREAD

**Issue by wallace46886799** [jeecgboot/jeecgboot-vue3#311]
##### 版本号：
3.4.4

##### 问题描述：
在线表单的自定义按钮无法使用多行选择

##### 截图&代码：
runtime-core.esm-bundler.js:220 Uncaught TypeError: Cannot read properties of undefined (reading 'selectionRows')
    at Proxy.batch_first_interview (eval at initCgEnhanceJs (useAutoForm.js:495:17), <anonymous>:33:50)
    at Proxy.execButtonEnhance (useListButton.js:174:54)
    at Proxy.cgButtonJsHandler (useListButton.js:865:24)
    at onClick (OnlineAutoList.js:384:41)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:21)
    at emit$1 (runtime-core.esm-bundler.js:720:9)
    at runtime-core.esm-bundler.js:7412:53
    at handleClick2 (button.js:102:7)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
![image](https://user-images.githubusercontent.com/1111812/209148691-33608cd2-da6c-42f5-b7d2-20cf5a899a04.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by tygithub1** [comment]
不支持
