### ISSUE TITLE
jeecgboot-vue3运行报错。

### ISSUE THREAD

**Issue by wangliang7730** [jeecgboot/jeecgboot-vue3#341]
##### 版本号：
PS F:\Java\jeecgboot-vue3-master> node -v
v14.17.0

PS F:\Java\jeecgboot-vue3-master> pnpm -v
7.26.0

PS F:\Java\jeecgboot-vue3-master> npm -v
6.14.13

PS F:\Java\jeecgboot-vue3-master> vue -V
@vue/cli 4.5.13

PS F:\Java\jeecgboot-vue3-master> yarn -v
1.22.19

vscode 运行 pnpm run dev  报错
##### 问题描述：
F:/Java/jeecgboot-vue3-master/src/components/Form/src/jeecg/components/JSwitch.vue
3  |      <a-select
4  |        v-if="query"
5  |        v-model:value="value"
   |       ^^^^^
6  |        :options="selectOptions"
7  |        :disabled="disabled"

    at createCompilerError (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-core@3.2.45\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:18:19)
    at Object.transformModel (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-core@3.2.45\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:5267:25)
    at transformModel (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-dom@3.2.45\node_modules\@vue\compiler-dom\dist\compiler-dom.cjs.prod.js:2536:37)
    at buildProps (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-core@3.2.45\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:4655:48)
    at Array.postTransformElement (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-core@3.2.45\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:4294:38)
    at traverseNode (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-core@3.2.45\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2175:19)
    at traverseChildren (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-core@3.2.45\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2117:9)
    at traverseNode (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-core@3.2.45\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2168:13)
    at traverseNode (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-core@3.2.45\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2161:17)
    at traverseChildren (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-core@3.2.45\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2117:9)
    at traverseNode (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-core@3.2.45\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2168:13)
    at traverseChildren (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-core@3.2.45\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2117:9)
    at traverseNode (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-core@3.2.45\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2168:13)
    at transform (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-core@3.2.45\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2056:5)
    at Object.baseCompile (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-core@3.2.45\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:5589:5)
    at Object.compile (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-dom@3.2.45\node_modules\@vue\compiler-dom\dist\compiler-dom.cjs.prod.js:3043:25)
    at doCompileTemplate (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-sfc@3.2.45\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:3223:49)
    at compileTemplate (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-sfc@3.2.45\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:3196:16)
    at Object.compileScript (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vue+compiler-sfc@3.2.45\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:4461:59)
    at resolveScript (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vitejs+plugin-vue@2.3.4_vite@2.9.15+vue@3.2.45\node_modules\@vitejs\plugin-vue\dist\index.js:4188:31)
    at genScriptCode (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vitejs+plugin-vue@2.3.4_vite@2.9.15+vue@3.2.45\node_modules\@vitejs\plugin-vue\dist\index.js:4465:18)
    at transformMain (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vitejs+plugin-vue@2.3.4_vite@2.9.15+vue@3.2.45\node_modules\@vitejs\plugin-vue\dist\index.js:4357:43)
    at Object.transform (F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+@vitejs+plugin-vue@2.3.4_vite@2.9.15+vue@3.2.45\node_modules\@vitejs\plugin-vue\dist\index.js:4739:16)
    at F:\Java\jeecgboot-vue3-master\node_modules\.pnpm\registry.npmmirror.com+rollup@2.79.1\node_modules\rollup\dist\shared\rollup.js:22879:40

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by wangliang7730** [comment]
两个月之前下载的代码，查看最新代码，发现JSwitch.vue已经修改，问题解决了。关闭问题。
