### ISSUE TITLE
vite打包报错

### ISSUE THREAD

**Issue by 1033965** [jeecgboot/jeecgboot-vue3#449]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/105904512/229749693-3f388aaa-7a04-4f53-b94c-62a43a88cd5a.png)

[vite]: Rollup failed to resolve import "@/components/echarts/echarts.vue" from "src/views/newDc/powerList.vue".                                                              18:13:37  
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

Error: [vite]: Rollup failed to resolve import "@/components/echarts/echarts.vue" from "src/views/newDc/powerList.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///E:/sggl/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45832:19)
    at onwarn (file:///E:/sggl/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45603:13)
    at Object.onwarn (file:///E:/sggl/node_modules/rollup/dist/es/shared/rollup.js:23263:13)
    at ModuleLoader.handleResolveId (file:///E:/sggl/node_modules/rollup/dist/es/shared/rollup.js:22158:26)
    at file:///E:/sggl/node_modules/rollup/dist/es/shared/rollup.js:22119:26

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这是你自己写的代码问题
