### ISSUE TITLE
我的部门-添加已有用户  打不开

### ISSUE THREAD

**Issue by ShellMount** [jeecgboot/jeecgboot-vue3#62]
##### 版本号：
v1.0.0

##### 问题描述：
我的部门-添加已有用户  打不开，一直在转

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12572507/166858276-1148ae0a-78f4-4853-8388-85b3289285e1.png)

```
PromiseRejectionEvent {isTrusted: true, reason: TypeError: Cannot read properties of undefined (reading 'indexOf')
    at http://localhost:3100/nod…, type: 'unhandledrejection', target: Window, currentTarget: Window, …}
SelectionCheckboxAll.js:23 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf')
    at SelectionCheckboxAll.js:23:34
    at Array.every (<anonymous>)
    at checkSelection (SelectionCheckboxAll.js:22:13)
    at getCheckState (SelectionCheckboxAll.js:77:10)
    at ReactiveEffect.fn (SelectionCheckboxAll.js:97:16)
    at ReactiveEffect.run (reactivity.esm-bundler.js:160:29)
    at ComputedRefImpl.get value [as value] (reactivity.esm-bundler.js:1086:39)
    at unref (reactivity.esm-bundler.js:1000:29)
    at Object.get (reactivity.esm-bundler.js:1003:37)
    at Object.get (runtime-core.esm-bundler.js:5945:32)
(匿名) @ SelectionCheckboxAll.js:23
checkSelection @ SelectionCheckboxAll.js:22
getCheckState @ SelectionCheckboxAll.js:77
(匿名) @ SelectionCheckboxAll.js:97
run @ reactivity.esm-bundler.js:160
get value @ reactivity.esm-bundler.js:1086
unref @ reactivity.esm-bundler.js:1000
get @ reactivity.esm-bundler.js:1003
get @ runtime-core.esm-bundler.js:5945
render135 @ SelectionCheckboxAll.js:144
renderComponentRoot @ runtime-core.esm-bundler.js:460
componentUpdateFn @ runtime-core.esm-bundler.js:4295
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4165
processComponent @ runtime-core.esm-bundler.js:4098
patch @ runtime-core.esm-bundler.js:3689
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
patchElement @ runtime-core.esm-bundler.js:3918
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
patchElement @ runtime-core.esm-bundler.js:3918
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
patchElement @ runtime-core.esm-bundler.js:3918
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
processFragment @ runtime-core.esm-bundler.js:4083
patch @ runtime-core.esm-bundler.js:3682
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
patchElement @ runtime-core.esm-bundler.js:3918
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
processFragment @ runtime-core.esm-bundler.js:4083
patch @ runtime-core.esm-bundler.js:3682
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
patchElement @ runtime-core.esm-bundler.js:3918
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
componentUpdateFn @ runtime-core.esm-bundler.js:4304
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4165
processComponent @ runtime-core.esm-bundler.js:4098
patch @ runtime-core.esm-bundler.js:3689
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
processFragment @ runtime-core.esm-bundler.js:4083
patch @ runtime-core.esm-bundler.js:3682
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
patchElement @ runtime-core.esm-bundler.js:3918
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
componentUpdateFn @ runtime-core.esm-bundler.js:4304
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4165
processComponent @ runtime-core.esm-bundler.js:4098
patch @ runtime-core.esm-bundler.js:3689
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
patchElement @ runtime-core.esm-bundler.js:3918
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
componentUpdateFn @ runtime-core.esm-bundler.js:4304
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4165
processComponent @ runtime-core.esm-bundler.js:4098
patch @ runtime-core.esm-bundler.js:3689
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
patchElement @ runtime-core.esm-bundler.js:3918
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
componentUpdateFn @ runtime-core.esm-bundler.js:4304
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4165
processComponent @ runtime-core.esm-bundler.js:4098
patch @ runtime-core.esm-bundler.js:3689
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
processFragment @ runtime-core.esm-bundler.js:4083
patch @ runtime-core.esm-bundler.js:3682
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
processFragment @ runtime-core.esm-bundler.js:4083
patch @ runtime-core.esm-bundler.js:3682
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
patchElement @ runtime-core.esm-bundler.js:3918
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
componentUpdateFn @ runtime-core.esm-bundler.js:4304
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4165
processComponent @ runtime-core.esm-bundler.js:4098
patch @ runtime-core.esm-bundler.js:3689
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
patchElement @ runtime-core.esm-bundler.js:3918
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
patchElement @ runtime-core.esm-bundler.js:3918
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
processFragment @ runtime-core.esm-bundler.js:4083
patch @ runtime-core.esm-bundler.js:3682
componentUpdateFn @ runtime-core.esm-bundler.js:4304
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4165
processComponent @ runtime-core.esm-bundler.js:4098
patch @ runtime-core.esm-bundler.js:3689
componentUpdateFn @ runtime-core.esm-bundler.js:4304
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4165
processComponent @ runtime-core.esm-bundler.js:4098
patch @ runtime-core.esm-bundler.js:3689
componentUpdateFn @ runtime-core.esm-bundler.js:4304
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4165
processComponent @ runtime-core.esm-bundler.js:4098
patch @ runtime-core.esm-bundler.js:3689
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
processFragment @ runtime-core.esm-bundler.js:4083
patch @ runtime-core.esm-bundler.js:3682
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
patchElement @ runtime-core.esm-bundler.js:3918
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
patchElement @ runtime-core.esm-bundler.js:3918
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
componentUpdateFn @ runtime-core.esm-bundler.js:4304
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4165
processComponent @ runtime-core.esm-bundler.js:4098
patch @ runtime-core.esm-bundler.js:3689
patchKeyedChildren @ runtime-core.esm-bundler.js:4459
patchChildren @ runtime-core.esm-bundler.js:4402
patchElement @ runtime-core.esm-bundler.js:3918
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
componentUpdateFn @ runtime-core.esm-bundler.js:4304
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4165
processComponent @ runtime-core.esm-bundler.js:4098
patch @ runtime-core.esm-bundler.js:3689
componentUpdateFn @ runtime-core.esm-bundler.js:4304
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4165
processComponent @ runtime-core.esm-bundler.js:4098
patch @ runtime-core.esm-bundler.js:3689
patchBlockChildren @ runtime-core.esm-bundler.js:4003
patchElement @ runtime-core.esm-bundler.js:3911
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
componentUpdateFn @ runtime-core.esm-bundler.js:4304
run @ reactivity.esm-bundler.js:160
callWithErrorHandling @ runtime-core.esm-bundler.js:6701
flushJobs @ runtime-core.esm-bundler.js:6940
Promise.then(异步)
nextTick @ runtime-core.esm-bundler.js:6792
setState @ BaseMixin.js:28
handler5 @ Table.js:183
callWithErrorHandling @ runtime-core.esm-bundler.js:6701
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6710
job @ runtime-core.esm-bundler.js:7118
flushPreFlushCbs @ runtime-core.esm-bundler.js:6874
updateComponentPreRender @ runtime-core.esm-bundler.js:4365
componentUpdateFn @ runtime-core.esm-bundler.js:4277
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4165
processComponent @ runtime-core.esm-bundler.js:4098
patch @ runtime-core.esm-bundler.js:3689
componentUpdateFn @ runtime-core.esm-bundler.js:4304
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4165
processComponent @ runtime-core.esm-bundler.js:4098
patch @ runtime-core.esm-bundler.js:3689
patchBlockChildren @ runtime-core.esm-bundler.js:4003
patchElement @ runtime-core.esm-bundler.js:3911
processElement @ runtime-core.esm-bundler.js:3769
patch @ runtime-core.esm-bundler.js:3686
componentUpdateFn @ runtime-core.esm-bundler.js:4304
run @ reactivity.esm-bundler.js:160
callWithErrorHandling @ runtime-core.esm-bundler.js:6701
flushJobs @ runtime-core.esm-bundler.js:6940
Promise.then(异步)
queueFlush @ runtime-core.esm-bundler.js:6831
queueCb @ runtime-core.esm-bundler.js:6853
queuePreFlushCb @ runtime-core.esm-bundler.js:6856
scheduler @ runtime-core.esm-bundler.js:7146
triggerEffects @ reactivity.esm-bundler.js:358
triggerRefValue @ reactivity.esm-bundler.js:948
set value @ reactivity.esm-bundler.js:992
fetch @ useDataSource.ts:305
await in fetch(异步)
(匿名) @ useDataSource.ts:348
watch.immediate @ useTimeout.ts:17
callWithErrorHandling @ runtime-core.esm-bundler.js:6701
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6710
job @ runtime-core.esm-bundler.js:7118
flushPreFlushCbs @ runtime-core.esm-bundler.js:6874
flushJobs @ runtime-core.esm-bundler.js:6915
Promise.then(异步)
queueFlush @ runtime-core.esm-bundler.js:6831
queueCb @ runtime-core.esm-bundler.js:6853
queuePreFlushCb @ runtime-core.esm-bundler.js:6856
scheduler @ runtime-core.esm-bundler.js:7146
triggerEffects @ reactivity.esm-bundler.js:358
triggerRefValue @ reactivity.esm-bundler.js:948
set value @ reactivity.esm-bundler.js:992
(匿名) @ useTimeout.ts:36
setTimeout(异步)
start @ useTimeout.ts:35
useTimeoutRef @ useTimeout.ts:40
useTimeoutFn @ useTimeout.ts:10
(匿名) @ useDataSource.ts:347
callWithErrorHandling @ runtime-core.esm-bundler.js:6701
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6710
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:1964
flushPostFlushCbs @ runtime-core.esm-bundler.js:6902
flushJobs @ runtime-core.esm-bundler.js:6947
Promise.then(异步)
queueFlush @ runtime-core.esm-bundler.js:6831
queueJob @ runtime-core.esm-bundler.js:6825
(匿名) @ runtime-core.esm-bundler.js:4336
triggerEffects @ reactivity.esm-bundler.js:358
triggerRefValue @ reactivity.esm-bundler.js:948
set value @ reactivity.esm-bundler.js:992
(匿名) @ runtime-core.esm-bundler.js:1630
Promise.then(异步)
setup @ runtime-core.esm-bundler.js:1629
callWithErrorHandling @ runtime-core.esm-bundler.js:6701
setupStatefulComponent @ runtime-core.esm-bundler.js:6310
setupComponent @ runtime-core.esm-bundler.js:6266
mountComponent @ runtime-core.esm-bundler.js:4119
processComponent @ runtime-core.esm-bundler.js:4094
patch @ runtime-core.esm-bundler.js:3689
mountChildren @ runtime-core.esm-bundler.js:3885
processFragment @ runtime-core.esm-bundler.js:4053
patch @ runtime-core.esm-bundler.js:3682
mountChildren @ runtime-core.esm-bundler.js:3885
mountElement @ runtime-core.esm-bundler.js:3794
processElement @ runtime-core.esm-bundler.js:3766
patch @ runtime-core.esm-bundler.js:3686
componentUpdateFn @ runtime-core.esm-bundler.js:4234
run @ reactivity.esm-bundler.js:160
setupRenderEffect @ runtime-core.esm-bundler.js:4353
mountComponent @ runtime-core.esm-bundler.js:4136
processComponent @ runtime-core.esm-bundler.js:4094
patch @ runtime-core.esm-bundler.js:3689
mountChildren @ runtime-core.esm-bundler.js:3885
processFragment @ runtime-core.esm-bundler.js:4053
patch @ runtime-core.esm-bundler.js:3682
mountChildren @ runtime-core.esm-bundler.js:3885
mountElement @ runtime-core.esm-bundler.js:3794
processElement @ runtime-core.esm-bundler.js:3766
patch @ runtime-core.esm-bundler.js:3686
componentUpdateFn @ runtime-core.esm-bundler.js:4234
run @ reactivity.esm-bundler.js:160
setupRenderEffect @ runtime-core.esm-bundler.js:4353
mountComponent @ runtime-core.esm-bundler.js:4136
processComponent @ runtime-core.esm-bundler.js:4094
patch @ runtime-core.esm-bundler.js:3689
mountChildren @ runtime-core.esm-bundler.js:3885
processFragment @ runtime-core.esm-bundler.js:4053
patch @ runtime-core.esm-bundler.js:3682
mountChildren @ runtime-core.esm-bundler.js:3885
processFragment @ runtime-core.esm-bundler.js:4053
patch @ runtime-core.esm-bundler.js:3682
mountChildren @ runtime-core.esm-bundler.js:3885
mountElement @ runtime-core.esm-bundler.js:3794
processElement @ runtime-core.esm-bundler.js:3766
patch @ runtime-core.esm-bundler.js:3686
mountChildren @ runtime-core.esm-bundler.js:3885
processFragment @ runtime-core.esm-bundler.js:4053
patch @ runtime-core.esm-bundler.js:3682
mountChildren @ runtime-core.esm-bundler.js:3885
processFragment @ runtime-core.esm-bundler.js:4053
patch @ runtime-core.esm-bundler.js:3682
mountChildren @ runtime-core.esm-bundler.js:3885
mountElement @ runtime-core.esm-bundler.js:3794
processElement @ runtime-core.esm-bundler.js:3766
patch @ runtime-core.esm-bundler.js:3686
mountChildren @ runtime-core.esm-bundler.js:3885
mountElement @ runtime-core.esm-bundler.js:3794
processElement @ runtime-core.esm-bundler.js:3766
patch @ runtime-core.esm-bundler.js:3686
mountChildren @ runtime-core.esm-bundler.js:3885
mountElement @ runtime-core.esm-bundler.js:3794
processElement @ runtime-core.esm-bundler.js:3766
patch @ runtime-core.esm-bundler.js:3686
componentUpdateFn @ runtime-core.esm-bundler.js:4234
run @ reactivity.esm-bundler.js:160
setupRenderEffect @ runtime-core.esm-bundler.js:4353
mountComponent @ runtime-core.esm-bundler.js:4136
processComponent @ runtime-core.esm-bundler.js:4094
patch @ runtime-core.esm-bundler.js:3689
componentUpdateFn @ runtime-core.esm-bundler.js:4234
run @ reactivity.esm-bundler.js:160
setupRenderEffect @ runtime-core.esm-bundler.js:4353
mountComponent @ runtime-core.esm-bundler.js:4136
processComponent @ runtime-core.esm-bundler.js:4094
patch @ runtime-core.esm-bundler.js:3689
componentUpdateFn @ runtime-core.esm-bundler.js:4234
run @ reactivity.esm-bundler.js:160
setupRenderEffect @ runtime-core.esm-bundler.js:4353
mountComponent @ runtime-core.esm-bundler.js:4136
processComponent @ runtime-core.esm-bundler.js:4094
patch @ runtime-core.esm-bundler.js:3689
mountChildren @ runtime-core.esm-bundler.js:3885
processFragment @ runtime-core.esm-bundler.js:4053
patch @ runtime-core.esm-bundler.js:3682
mountChildren @ runtime-core.esm-bundler.js:3885
mountElement @ runtime-core.esm-bundler.js:3794
processElement @ runtime-core.esm-bundler.js:3766
patch @ runtime-core.esm-bundler.js:3686
mountChildren @ runtime-core.esm-bundler.js:3885
mountElement @ runtime-core.esm-bundler.js:3794
processElement @ runtime-core.esm-bundler.js:3766
patch @ runtime-core.esm-bundler.js:3686
mountChildren @ runtime-core.esm-bundler.js:3885
processFragment @ runtime-core.esm-bundler.js:4053
patch @ runtime-core.esm-bundler.js:3682
mountChildren @ runtime-core.esm-bundler.js:3885
mountElement @ runtime-core.esm-bundler.js:3794
processElement @ runtime-core.esm-bundler.js:3766
patch @ runtime-core.esm-bundler.js:3686
componentUpdateFn @ runtime-core.esm-bundler.js:4234
run @ reactivity.esm-bundler.js:160
setupRenderEffect @ runtime-core.esm-bundler.js:4353
mountComponent @ runtime-core.esm-bundler.js:4136
processComponent @ runtime-core.esm-bundler.js:4094
patch @ runtime-core.esm-bundler.js:3689
componentUpdateFn @ runtime-core.esm-bundler.js:4234
run @ reactivity.esm-bundler.js:160
setupRenderEffect @ runtime-core.esm-bundler.js:4353
mountComponent @ runtime-core.esm-bundler.js:4136
processComponent @ runtime-core.esm-bundler.js:4094
patch @ runtime-core.esm-bundler.js:3689
componentUpdateFn @ runtime-core.esm-bundler.js:4234
run @ reactivity.esm-bundler.js:160
setupRenderEffect @ runtime-core.esm-bundler.js:4353
mountComponent @ runtime-core.esm-bundler.js:4136
processComponent @ runtime-core.esm-bundler.js:4094
patch @ runtime-core.esm-bundler.js:3689
mountChildren @ runtime-core.esm-bundler.js:3885
mountElement @ runtime-core.esm-bundler.js:3794
processElement @ runtime-core.esm-bundler.js:3766
patch @ runtime-core.esm-bundler.js:3686
mountChildren @ runtime-core.esm-bundler.js:3885
mountElement @ runtime-core.esm-bundler.js:3794
processElement @ runtime-core.esm-bundler.js:3766
patch @ runtime-core.esm-bundler.js:3686
componentUpdateFn @ runtime-core.esm-bundler.js:4234
run @ reactivity.esm-bundler.js:160
setupRenderEffect @ runtime-core.esm-bundler.js:4353
mountComponent @ runtime-core.esm-bundler.js:4136
processComponent @ runtime-core.esm-bundler.js:4094
patch @ runtime-core.esm-bundler.js:3689
mountChildren @ runtime-core.esm-bundler.js:3885
mount @ runtime-core.esm-bundler.js:5092
process @ runtime-core.esm-bundler.js:5099
patch @ runtime-core.esm-bundler.js:3692
componentUpdateFn @ runtime-core.esm-bundler.js:4304
run @ reactivity.esm-bundler.js:160
callWithErrorHandling @ runtime-core.esm-bundler.js:6701
flushJobs @ runtime-core.esm-bundler.js:6940
flushJobs @ runtime-core.esm-bundler.js:6955
Promise.then(异步)
queueFlush @ runtime-core.esm-bundler.js:6831
queueJob @ runtime-core.esm-bundler.js:6825
(匿名) @ runtime-core.esm-bundler.js:4336
triggerEffects @ reactivity.esm-bundler.js:358
triggerRefValue @ reactivity.esm-bundler.js:948
(匿名) @ reactivity.esm-bundler.js:1075
triggerEffects @ reactivity.esm-bundler.js:358
triggerRefValue @ reactivity.esm-bundler.js:948
(匿名) @ reactivity.esm-bundler.js:1075
triggerEffects @ reactivity.esm-bundler.js:358
triggerRefValue @ reactivity.esm-bundler.js:948
set value @ reactivity.esm-bundler.js:992
setModalProps @ BasicModal.vue:195
openModal @ useModal.ts:79
selectAddUser @ DepartUserInfoTab.vue:161
callWithErrorHandling @ runtime-core.esm-bundler.js:6701
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6710
emit$1 @ runtime-core.esm-bundler.js:285
(匿名) @ runtime-core.esm-bundler.js:6486
handleClick6 @ button.js:119
callWithErrorHandling @ runtime-core.esm-bundler.js:6701
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6710
invoker @ runtime-dom.esm-bundler.js:350
Show 285 more frames
index.ts:67 PromiseRejectionEvent {isTrusted: true, reason: TypeError: Cannot read properties of undefined (reading 'indexOf')
    at http://localhost:3100/nod…, type: 'unhandledrejection', target: Window, currentTarget: Window, …}
SelectionCheckboxAll.js:23 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf')
    at SelectionCheckboxAll.js:23:34
    at Array.every (<anonymous>)
    at checkSelection (SelectionCheckboxAll.js:22:13)
    at getCheckState (SelectionCheckboxAll.js:77:10)
    at ReactiveEffect.fn (SelectionCheckboxAll.js:97:16)
    at ReactiveEffect.run (reactivity.esm-bundler.js:160:29)
    at ComputedRefImpl.get value [as value] (reactivity.esm-bundler.js:1086:39)
    at unref (reactivity.esm-bundler.js:1000:29)
    at Object.get (reactivity.esm-bundler.js:1003:37)
    at Object.get (runtime-core.esm-bundler.js:5945:32)
```

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
把代码更新到最新看看

**Comment by ShellMount** [comment]
@zhangdaiscott 

我下的是5.2号的代码。你们最近几天没有更新。

应该就是最新的代码了。

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
