### ISSUE TITLE
pnpm build打包错误，报Rollup failed to resolve import *** from ****错误

### ISSUE THREAD

**Issue by XuJianDeCat** [jeecgboot/jeecgboot-vue3#919]
##### 版本号：

  "name": "jeecgboot-vue3",
  "version": "3.5.3",
node 版本 **16.18.0**
##### 问题描述：
我在用 pnpm build 指令打包的时候出现**找不到模块“html2canvas”或其相应的类型声明**的错误。
我也在Issues上看见过别人也出现了跟我**同理**的错误，但是并不是一样的错误。具体看下图。
其次，这个代码模块并不是我自己写的，不是我自己写的，这个JeecgBoot自己自带的功能。
1、那意思是没有这个依赖呗，也不对，这个依赖有，在**node_modules\.pnpm\registry.npmmirror.com+html2canvas@1.4.1\node_modules\html2canvas**文件夹下。
2、**我如果把它注释掉，就可以打包成功。**如下图
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127873967/8d018220-5e55-4fc0-a96e-a63db15eef1c)

 ERROR  [vite]: Rollup failed to resolve import "html2canvas" from "src/views/super/drag/page/useExportImage.ts".   15:13:26  
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

 ERROR  error during build:                                                                                         15:13:26  
Error: [vite]: Rollup failed to resolve import "html2canvas" from "src/views/super/drag/page/useExportImage.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///E:/%E7%94%B5%E7%8E%A9%E5%9B%A2%E9%98%9F-%E5%B0%8F%E5%85%AB%E5%93%A5%E9%A1%B9%E7%9B%AE/%E5%90%8E%E5%8F%B0%E7%9A%84%E5%89%8D%E7%AB%AFv2/platform-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.0.2_less@4.1.2_terser@5.19.2/node_modules/vite/dist/node/chunks/dep-1513d487.js:43558:19)
    at onwarn (file:///E:/%E7%94%B5%E7%8E%A9%E5%9B%A2%E9%98%9F-%E5%B0%8F%E5%85%AB%E5%93%A5%E9%A1%B9%E7%9B%AE/%E5%90%8E%E5%8F%B0%E7%9A%84%E5%89%8D%E7%AB%AFv2/platform-admin/node_modules/.pnpm/registry.npmmirror.com+vite@3.0.2_less@4.1.2_terser@5.19.2/node_modules/vite/dist/node/chunks/dep-1513d487.js:43349:13)
    at Object.onwarn (file:///E:/%E7%94%B5%E7%8E%A9%E5%9B%A2%E9%98%9F-%E5%B0%8F%E5%85%AB%E5%93%A5%E9%A1%B9%E7%9B%AE/%E5%90%8E%E5%8F%B0%E7%9A%84%E5%89%8D%E7%AB%AFv2/platform-admin/node_modules/.pnpm/registry.npmmirror.com+rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:23263:13)
    at ModuleLoader.handleResolveId (file:///E:/%E7%94%B5%E7%8E%A9%E5%9B%A2%E9%98%9F-%E5%B0%8F%E5%85%AB%E5%93%A5%E9%A1%B9%E7%9B%AE/%E5%90%8E%E5%8F%B0%E7%9A%84%E5%89%8D%E7%AB%AFv2/platform-admin/node_modules/.pnpm/registry.npmmirror.com+rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22158:26)
    at file:///E:/%E7%94%B5%E7%8E%A9%E5%9B%A2%E9%98%9F-%E5%B0%8F%E5%85%AB%E5%93%A5%E9%A1%B9%E7%9B%AE/%E5%90%8E%E5%8F%B0%E7%9A%84%E5%89%8D%E7%AB%AFv2/platform-admin/node_modules/.pnpm/registry.npmmirror.com+rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22119:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 ELIFECYCLE  Command failed with exit code 1.
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127873967/68e6bf31-55c2-47f0-8f88-1ad7020961cb)
我如果把它注释掉，就可以打包成功。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不太清楚
